"""Add name fields to user

Revision ID: ec9e1450af58
Revises: b46c52f31803
Create Date: 2024-03-06 23:06:53.973618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9e1450af58'
down_revision: Union[str, None] = 'b46c52f31803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False, server_default=""))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False, server_default=""))
    op.add_column('users', sa.Column('middle_name', sa.String(length=100), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
